### ISSUE TITLE
misleading translation in fieldname (plural / singular)

### ISSUE THREAD

**Issue by KlausSchade** [mysql-workbench-schema-exporter/doctrine2-exporter#32]
Thank you for your work.
I'm using MySQL Workbench to create a Model.
One of the used tables is called "unternehmen" (it is german for "company").
I have a One-to-Many relation to "niederlassung".
When I create the entity classes with your tool the following happens:

1. The entity is called "unternehman" (a instead of e)
2. The annotation is:  @ORM\Table(name="unternehmen")

This is maybe a feature of auto translating plural/singular, but a little bit confusing.
What can I do to change this behavior, the entity has to have the same name as the table in the mwb-Model.

Thanks for your advice.

**Comment by johmue** [comment]
Hi,
Please check the configuration option `skipPluralNameChecking` it's also mentioned in the README.

Additionally I strongly recommend to create data models always in english, otherwise you limit your source to a smaller audience. If you build a business around your code it's also a hurdle for (in your case) non-german employees.

**Comment by KlausSchade** [comment]
Thank you.
I missed the readme / config of [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter](https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter), I only read mysql-workbench-schema-exporter/doctrine2-exporter
